### ISSUE TITLE
Signal-related test failures on MSWin32

### ISSUE THREAD

**Issue by eserte** [miyagawa/CGI-Compile#16]
See http://matrix.cpantesters.org/?dist=CGI-Compile;os=mswin32;reports=1 for a test overview.

**Comment by rkitover** [comment]
I'll take a look at this once I get my windows VM back up.

On March 1, 2015 at 9:00:42 AM, Slaven Rezić (notifications@github.com) wrote:

See http://matrix.cpantesters.org/?dist=CGI-Compile;os=mswin32;reports=1 for a test overview.

**Comment by rkitover** [comment]
Fixed in master, hopefully.

**Comment by miyagawa** [comment]
@eserte can you confirm?

**Comment by eserte** [comment]
Yes, master tests fine with StrawberryPerl 5.20.1.

**Comment by miyagawa** [comment]
Cool, shipped 0.19
