### ISSUE TITLE
Signal-related test failure in Jenkins job

### ISSUE THREAD

**Issue by lemrouch** [miyagawa/CGI-Compile#19]
I'm trying to install CGI::Compile module in Jenkins job and local-SIG test fails on:
```
#   Failed test 'caught signal'
#   at t/local-SIG.t line 18.
#          got: 'END
# '
#     expected: 'QUIT
# END
# '
# Looks like you failed 1 test of 1.
t/local-SIG.t .......... 
```
Since Jenkins masks QUIT signal I had to unmask it in test.
[CGI-Compile-0.21.patch.txt](https://github.com/miyagawa/CGI-Compile/files/745306/CGI-Compile-0.21.patch.txt)

Is it possible to have something like this worked in please?

**Comment by miyagawa** [comment]
This seems reasonable - can you submit a pull request?

**Comment by lemrouch** [comment]
Something like #20 ?

**Comment by miyagawa** [comment]
Yep, thanks!
