### ISSUE TITLE
Race condition in tmp dir creation with PSGI

### ISSUE THREAD

**Issue by jr-dimedis** [miyagawa/CGI-Compile#24]
From time to time we encounter crashes when using CGI::Compile 0.22 in a PSGI persistent environment.

`Could not mkdir /tmp/cgi_compile_29585: File exists at /usr/share/perl5/CGI/Compile.pm line 177.`

We tracked this down to a lexical static variable for the tmp dir containing the process id. In a forked context all children share the same tmp directory. The race comes from checking for existence of the directory before creating it and crashing if the latter fails because another child created it already in the meantime.

Attached you find a fix for this issue. Each child has it's own tmp dir so no clashing is possible.

[CGI-Compile-0.22-fix-tmp-race-condition.txt](https://github.com/miyagawa/CGI-Compile/files/3190903/CGI-Compile-0.22-fix-tmp-race-condition.txt)

Looking forward to a CPAN release containing this fix :)

Thanks!

Jörn

**Comment by rkitover** [comment]
I will take care of this and the other outstanding PRs.

**Comment by jacquesg** [comment]
I've observed this behaviour as well. Any change of getting a fix in and a new release?

**Comment by rkitover** [comment]
@jr-dimedis sorry I'm finally getting back to this, what email address would you like to use for this commit, I can leave it blank as well.

**Comment by rkitover** [comment]
@jr-dimedis I added a test in c0a01bc and your commit in c0a01bc, thank you very much!

@miyagawa Can you please push a release, or add me as a comaint and I'll take care of it. Also I promised to look at some of the other outstanding issues, I will do that now.

**Comment by miyagawa** [comment]
@rkitover i gave you a comaint on CGI::Compile

**Comment by rkitover** [comment]
Travis is fixed.

**Comment by rkitover** [comment]
@jr-dimedis @jacquesg @miyagawa 

0.23 has been uploaded to CPAN with the fix and indexed successfully.

I will take care of any remaining issues, like the PRs over the next couple of weeks or so.

**Comment by rkitover** [comment]
@miyagawa 

0.24 is uploaded.

I've cleaned up all the PRs, issues and branches.

This repo should be good for another decade, if anything comes up I will try to pay more attention.
