### ISSUE TITLE
regression of sorts in 0.24

### ISSUE THREAD

**Issue by dakkar** [miyagawa/CGI-Compile#25]
Up to version 0.23, each CGI was compiled into its own package. Version 0.24 compiles all CGIs from the same directory into the same package.

This means that imports from `use`, `our` variables, and any other non lexical effects are now shared by different programs. Such sharing is unexpected and produces weird behaviours.

Is there a strong reason for that change? If not, could https://github.com/miyagawa/CGI-Compile/blob/b08e0bef9368f29fbd49e6fc7bb3080870af626a/lib/CGI/Compile.pm#L171 add `,$name` at the end of the `join`?

**Comment by rkitover** [comment]
Sorry I must have missed that, I was fixing some other issues, I will upload a new dist a bit later today.

**Comment by rkitover** [comment]
`0.25` is on CPAN with the fix, sorry about that.

**Comment by miyagawa** [comment]
Thanks for the quick fix!
